### ISSUE TITLE
[ISO] Explicitly spec that SFNT tables can overlap

### ISSUE THREAD

**Issue by behdad** [harfbuzz/boring-expansion-spec#113]
Useful for hybrid fonts.

**Comment by HinTak** [comment]
This one is going to be fun to break/hack as an attack vector.

**Comment by liamquin** [comment]
Added.

**Comment by HinTak** [comment]
It might be better to restrict this to some tables (the bigger tables), and also explicitly disallowing overlapping boundaries. i.e. only allow one table to wholy containing another, rather than genuinely overlapping, as in the beginning of table 1 is outside table 2, but ending within table 2.

I think the general desire is for one (old) table to be a wholy contained subset of another (new) table.

This might be far-fetched, but I don't think there is any allowance for non-contiguous tables at all? Anyway, I think the one table being "wholy contained" within another is not much of a restriction, but will save a lot of headaches down stream.

**Comment by behdad** [comment]
> It might be better to restrict this to some tables (the bigger tables), and also explicitly disallowing overlapping boundaries. i.e. only allow one table to wholy containing another, rather than genuinely overlapping, as in the beginning of table 1 is outside table 2, but ending within table 2.

What's the rationale for introducing this restriction?

**Comment by HinTak** [comment]
Does genuine overlap give you anything substantially more than 'one wholy containing within another' (if size saving is the main motivation)? I am concerned about all the security implications of actually allowing arbitrary overlap.

Does your prototype use case actually use 'genuine overlap', versus 'one wholy containing/subsetting within another'?

**Comment by behdad** [comment]
My prototype does not use any overlap.

It's a difference in philosophy. I'm for simplicity and less unnecessary restrictions.

**Comment by HinTak** [comment]
That's not how I see it - the original spec disallow overlaps, full-stop. You are proposing relaxing all the way to allow random overlap. I am saying the relaxing partially, of some kind of overlap, those that's where one table sits entirely without another.

The original spec of disallowing any overlaps were done for many good reasons then, and relaxing all the way is likely to break a lot of things, and also creating a lot of security holes. I am suggesting relaxing the original restrictions only as much as your new needs (of saving bytes) requires. This is good security practice.

**Comment by behdad** [comment]
> The original spec of disallowing any overlaps were done for many good reasons then

Can you list any of those "good reasons"?

**Comment by HinTak** [comment]
You are probably being argumentative... Anyway, as a random example, did people really want, say, the possibility/horror of having the ending part of the `hmtx` table also re-used, or re-usable as the beginning part of the `loca` table? Do they want that kind of possibility/horrow now?

**Comment by behdad** [comment]
I'm not being argumentative. As I said already:

It's a difference in philosophy. I'm for simplicity and less unnecessary restrictions.

I'm not going to respond anymore.

**Comment by HinTak** [comment]
There is a 30+-year old restriction. You are proposing relaxing/removing it all the way. I am suggesting relaxing the age-old restriction only as much as new needs require, to avoid surprises from all parties.

We'll agree to disagree on this, I guess.

**Comment by cmyr** [comment]
I also would like to know if there is a more definite rationale for this idea than a vague notion of simplicity? Knowing that tables do not overlap does come with some benefit, such as knowing that a pointer into one table cannot be aliased by any pointer into any other table. This would be an important invariant for me if I wanted to (for instance) allow in-place mutation of raw font data in Rust, which is something one could reasonably want.

Similarly, knowing that tables cannot overlap simplifies graph packing (although could possibly miss out on some extra deduplication in some cases.)

**Comment by behdad** [comment]
But as part of the changes we are introducing, we want to allow table sharing in parts. In particular, eg. the glyf and GLYF tables might point to the same start and have differing lengths...

The disagreement is on whether it should be restricted further or not.

**Comment by HinTak** [comment]
glyf and GLYF having the same start and different length, is still one whole contained within the other. It is sufficient for your purpose.

The disagreement is on whether to RELAXING the 30-years of existing restrictions further.

**Comment by cmyr** [comment]
Okay, thanks.

From the point of view of someone who has spent quite a bit of time thinking about how to parse these tables, I think in the general case keeping them disjoint has some value. Allowing for new tables to be supersets of older tables sounds fine. A general relaxation feels like it would mostly be confusing, since in practice I can't imagine we would actually start making (say) GPOS/GSUB overlap in the foreseeable future.


(I appreciate I have not participated much in this project to date, and I accept as a consequence of this that my voice may be somewhat discounted 😉)

**Comment by HinTak** [comment]
My concern of relaxing the existing 30+-years of restrictions all the way is in the way both external tools and rasterizer's internal safe-guards on disjointed data. It is relatively easy to check for disjointed data (and throw away "suspicious" data). Allowing for old table to be wholy contained within a bigger table is sufficient for the newer emerging needs. Relaxing further, is going to cause a lot of trouble, such as the possibility/horror of part of GPOS being (mis-)interpreted as GSUB, etc.

**Comment by HinTak** [comment]
Particularly in the intended usage of some of the folks pushing for this change - web fonts with very dubious overlapping tables are coming from afar and arriving at your computer, when you visit a web site you may or may not trust.
