### ISSUE TITLE
[ISO] Add `MAXP` duplicate of `maxp` but with 24-bit numGlyphs

### ISSUE THREAD

**Issue by behdad** [harfbuzz/boring-expansion-spec#114]
Both 0.5 and 1.0 versions to be duplicated and updated. Everything else remains the same.

**Comment by behdad** [comment]
For implementations that understand `MAXP`, it supersedes `maxp`.

**Comment by liamquin** [comment]
[[ (draft text)
MAXP—Maximum Profile, for 24-bit fonts

This table mirrors the ‘maxp’ table, but for fonts in which GlyphID values are represented as 24-bit integers; the older ‘maxp’ table assumes 16-bit values. Fonts containing both ‘MAXP’ and ‘maxp’ tables are said to be hybrid. They will work as 16-bit fonts in older software, and newer software will use the newer tables, typically ‘GLYF’ instead of, or alongside, ‘glyf’. However, older software will not of course be able to access more than 65535 glyphs in a font, will not be able to use the newer features allowed in glyph definitions found in the ‘GLYF’ table (such as cubic curves), and likely will not be able to access new features such as AVAR 2, so the user experience may be limited, as is also the case with software that does not support features such as swash (SWSH) or small caps (SMCP).

As with ‘maxp’ the values in the table are intended to establish memory requirements for the font. However, implementers are warned that the values may be inaccurate or maliciously incorrect.

Fonts with CFF or CFF2 outlines shall use Version 0.5 of this table, specifying only the numGlyphs field. Fonts with TrueType outlines must use Version 1.0 of this table, where all data is required.

Software supporting MAXP shall ignore maxp where both tables are present.
]]
