### ISSUE TITLE
[`glyf`] Cubic Bezier curves

### ISSUE THREAD

**Issue by behdad** [harfbuzz/boring-expansion-spec#41]
Use the last remaining bit of the simple-glyph flags bits:

* 0x80	CUBIC	Bit 7 Curve is cubic Bezier

The bit is only relevant for off-curve points. For on-curve points the value is _reserved_.

The number of consecutive off-curve points that have cubic flag on MUST be even. Every two off-curve points define one cubic Bezier.

The implicit-on-curve algorithm will extend to cubics. I'll expand on this in a followup comment or edit.

**Comment by Lorp** [comment]
For a cubic glyph, should the flag bit 7 be set to 1 on every point? I’m not clear if this proposal allows curve order to change within a glyph. (It would be nice to match SVG in this respect.)

If the intent is to have each glyph EITHER quadratic OR cubic, then it is wasteful to use bit 7 and an alternative method should be used. An obvious method would be to create a new field in `glyf`. An alternative that would not break existing tools could be to use dummy hints to represent new flag data, e.g. 0x81 0x7f 0x33 NPUSHB 0x03 CLEAR, but that’s likely a pain to parse fast.

**Comment by Lorp** [comment]
Here follows a proposal for handling multiple curve orders within a glyph. In summary, the method:

* Uses only bit 7 of the flag byte for each point of a simple glyph
* Handles TrueType curves (quadratic) with no changes
* Is reversible (if a contour’s direction is reversed, bits associated with curve order remain valid)
* Retains existing interpolation of implied on-curve point half way between the last off-curve points of one curve and first off-curve point of the successive curve
* Allows curves of order 3
* Allows curves of arbitrary order
* Allows contours of mixed order
* Keeps bit 6 free for other uses
* Keeps bit 7 for on-curve points free for other uses (e.g. smooth/corner status)

### Quadratic glyphs

Use the normal *glyf* representation. A TrueType glyph consisting only of closed contours is therefore stored in the standard OpenType format. Note that bit 7 must be 0 for all off-curve points in glyphs that are entirely quadratic or linear.

### Curves of higher order

We use bit 0 as usual, thus 1 = on-curve, 0 = off-curve. The first point of any contour must be on-curve. We now treat each curve group in the contour separately. A curve group is a sequence of 1 or more subcurves of heterogenous order, the group bounded by on-curve points. To determine the order of the subcurve(s) between the on-curve points, we use bit 7 to identify the first and last off-curve point of any subcurve. Bit 7 is therefore required in pairs. We also allow order 2 curves, by not setting bit 7 at all.

When parsing a contour, we step through the points from one on-curve point to the next on-curve point. When we encounter a set bit 7 flag, we are at either the first or the last off-curve point in a curve of order >=3. The curve order is determined by the number of points with unset bit 7 between the pair of points with set bit 7. For example, 0 points with unset bit 7 means 2 off-curve points, thus an order 3 curve; 2 points with unset bit 7 means 4 off-curve points, thus an order 5 curve. In general, the order of a curve bounded by two points with set bit 7 is 3 plus the number of consecutive points with unset bit 7.

We may also encounter points with unset bit 7 that are not bounded by a set bit 7 pair. These define curves of order 2, thus normal TrueType curves are a subset of this encoding. (Nerdily one can think of quadratic off-curve points, being both the first and last off-curve point of their curve, as having been set twice using XOR, resulting in 0.)

As with TrueType, two adjacent subcurves imply an interpolated on-curve point exactly half way between the neighbouring off-curve points.

### Examples

The following table shows various possibilities for curves between two on-curve points.

| Bit 0 | Bit 7 | Description | 
| --- | --- | --- |
| `101` | `000` | one quadratic curve |
| `10101` | `00000` | two quadratic curves |
| `1001` | `0000` | two quadratic curves, interpolating an on-curve point |
| `1001` | `0110` | one order 3 (cubic) curve  |
| `1001001` | `0110110` | two order 3 (cubic) curves  |
| `100001` | `011110` | two order 3 (cubic) curves, interpolating an intermediate on-curve point |
| `10001` | `01010` | one order 4 curve  |
| `10000001` | `01011010` | two order 4 curves, interpolating an intermediate on-curve point |
| `100001` | `010010` | an order 5 curve |
| `10000001` | `01000010` | an order 7 curve |
| `100000000001` | `010011000010` | an order 5 curve and an order 7 curve using interpolation for the on-curve point |
| `1000000001` | `0100100110` | an order 5 curve, two order 2 curves and an order 3 curve, interpolating on-curve points |

The last example, in words:
* we immediately encounter a bit 7, therefore we need to count the number of consecutive unset bit 7 points
* we count 2 consecutive points with unset bit 7, therefore we have a curve with order 5, defined by 6 points
* the first 5 points of this are points[0] to points[4]
* the 6th point is point half way between points[4] and points[5], and that’s also the first point of the next curve
* the next point is not within a bit 7 pair, therefore it’s quadratic, and the same applies to the point after that
* therefore we have two quadratic curves: the first is defined by that point between points[4] and points[5] we already determined, points[5] itself, and a point between points[5] and points[6]; the second is defined by that point between points[5] and points[6] that we just determined, points[6] itself, and a point between points[6] and points[7]
* we finally find another bit 7 pair, a cubic curve defined by the point between points[6] and points[7] we just determined, points[7], points[8] and points[9].

### Notes

* The requirement to start contours with an on-curve point ensures off-curve points are correctly grouped into pairs. We could in fact be a little looser, and (as with fully quadratic contours) allow starting with an off-curve point, but we would still need to ensure that the first off-curve point of each contour is the first off-curve point of a curve. Otherwise the off-curve pairs could be parsed “out of phase”.

* Note that while the proposed representation allows curves of order >3, I am not recommending here that such curves are allowed into the developing spec*.

### Parsing

To help parsing, it may be useful to cache curve order outside of the glyph flags. It is likely that entire fonts will be either cubic or quadratic. Even if mixed curve order is allowed within a glyph, it is likely that entire glyphs will be either cubic or quadratic. Perhaps a new table, compressed like cmap Format 4, would be useful to hold this cached data. Two bits per glyph would be useful, something like: 0=undefined?, 1=quadratic, 2=cubic, 3=quadratic & cubic.

**Comment by behdad** [comment]
Talking in another issue, @justvanrossum thinks that the implied on-curve is not a significant optimization for cubics. I'm going to try to measure this in some real font sources to get a sense.

*If* that was true and we wanted to forgo that, here's an alternative proposal that deviates from the current encoding model a bit but addresses most of our issues, though it wouldn't be reversible; maybe that one is not required after all.

We can set the 0x80 flag on an *on-curve* point, to mean that it's the start of a cubic segment, and the following two points will be its off-curve points *regardless of their flags*. This possibly allows for slightly better flag encoding since it wouldn't be constantly changing between on-curve/off-curve. Though that's probably negligible and would require a smart compiler to take advantage of.

I'm not in love with this encoding, but it does simplify things a bit.

**Comment by behdad** [comment]
Or we can say an 0x80 flag on an on-curve point means the following off-curve points form cubics. The only problem with this one is the odd number of off-curves. We can declare that one an error.

**Comment by behdad** [comment]
> Talking in another issue, @justvanrossum thinks that the implied on-curve is not a significant optimization for cubics. I'm going to try to measure this in some real font sources to get a sense.

Copying from https://github.com/fonttools/fonttools/issues/2989#issuecomment-1423193693:

I measured this for NotoSansArabic-MM. ~12% of the on-curve points matched and can be elided. That translates to maybe 3/4% total font size optimization. Given that I saw only 10% savings from adding cubics at all, that extra 3% is not too bad...

**Comment by behdad** [comment]
For NotoSans-MM it's just 6%.

**Comment by behdad** [comment]
If we wanted to specify on a per-contour basis whether all curves are cubic or quadratic we can borrow the top bit of the endPoint.

**Comment by behdad** [comment]
More and more I'm leaning towards the original proposal above.

**Comment by behdad** [comment]
Specing this at: https://github.com/harfbuzz/boring-expansion-spec/blob/main/glyf1-cubicOutlines.md

**Comment by Lorp** [comment]
Looks great. I’m pleased it is a subset of my spec for unlimited curve order above https://github.com/harfbuzz/boring-expansion-spec/issues/41#issuecomment-1014916070

I think it would be useful to cache whether glyphs are all quadratic, all cubic, or mixed, and to record this on a per glyph and (especially) a per font level. Such cached records will help systems decide how to convert for legacy environments.

**Comment by behdad** [comment]
> I think it would be useful to cache whether glyphs are all quadratic, all cubic, or mixed, and to record this on a per glyph and (especially) a per font level. Such cached records will help systems decide how to convert for legacy environments.

I don't think it's necessary. Every time we put cached values in the font, the implementation has to ignore it anyway since the cached values cannot be trusted.

**Comment by Lorp** [comment]
Fair enough.

**Comment by behdad** [comment]
> Specing this at: https://github.com/harfbuzz/boring-expansion-spec/blob/main/glyf1-cubicOutlines.md

@robmck-ms

**Comment by behdad** [comment]
Since the implementation was too hard. I simplified the spec to disallow mixing and matching quadratic and cubic between two on-curve points:

https://github.com/harfbuzz/boring-expansion-spec/blob/main/glyf1-cubicOutlines.md

**Comment by behdad** [comment]
Speced: https://github.com/harfbuzz/boring-expansion-spec/blob/main/glyf1-cubicOutlines.md
Implemented in HarfBuzz and FontTools.

**Comment by yisibl** [comment]
Good news, Fontlab 8 supports this feature.
https://help.fontlab.com/fontlab/8/whats-new/whats-new-11-formats/#export-static-opentype-fonts-with-a-cubic-glyf-table
